# Dockerfile

# 1. 从官方的 Elasticsearch 镜像开始
# 确保这里的版本号与您希望部署的版本一致
FROM docker.elastic.co/elasticsearch/elasticsearch:9.1.4

# 2. 在构建镜像的过程中，运行插件安装命令
# 这会在最终的镜像中包含 Kuromoji 插件
RUN bin/elasticsearch-plugin install analysis-kuromoji